In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [192]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # number of itteration
        
    
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs, weights)

    def activation_function(self,z):
        return np.where(z>0,1,0)

    def fit(self,X,y):
        self.X = X;
        self.y = y;
        
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"the bias is {X_with_bias}")

        for epoch in range(self.epochs):
            print("--"*10)
            print(f"For epoch >> {epoch+1}")
            print("--" * 10)

            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted Value after forward pass {y_hat}")

            self.error = self.y - y_hat
            print(f"Error: \n {self.error}")

            self.weights = self.weights + self.eta * np.dot(X_with_bias.T ,self.error)
            print(f"Updated weights after {epoch+1}/{self.epochs} : \n{self.weights} ")

            print("##"*10)

            
    def predict(self,X):
        X_with_bias = np.c_[X,-np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        y_hat = self.activation_function(z)
        return y_hat

In [193]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,1,0],
    "y" : [0,1,1,1]
}
df_or = pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   1  1
3   1   0  1

In [194]:
def prepare_data(df,target_col = "y"):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return X,y

In [199]:
X , y = prepare_data(df_or)

ETA = 0.11
EPOCHS = 10

model_or = Perceptron(ETA,EPOCHS)

model_or.fit(X,y)

the bias is [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  0. -1.]]
--------------------
For epoch >> 1
--------------------
Predicted Value after forward pass [0 1 1 1]
Error: 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after 1/10 : 
[1.73947960e-04 2.65898730e-04 2.03025821e-05] 
####################
--------------------
For epoch >> 2
--------------------
Predicted Value after forward pass [0 1 1 1]
Error: 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after 2/10 : 
[1.73947960e-04 2.65898730e-04 2.03025821e-05] 
####################
--------------------
For epoch >> 3
--------------------
Predicted Value after forward pass [0 1 1 1]
Error: 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after 3/10 : 
[1.73947960e-04 2.65898730e-04 2.03025821e-05] 
####################
--------------------
For epoch >> 4
--------------------
Predicted Value after forward pass [0 1 1 1]
Error: 
 0    0
1    0
2    0
3    0
Name: y,

In [200]:
model_or.predict(X)

array([0, 1, 1, 1])