In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [18]:
class Perception:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # number of itteration
        
        
    def fit(self,X,y):
        self.X = X;
        self.y = y;
        
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"the bias is {X_with_bias}")

In [19]:
obj = Perception(0.01,4)

In [24]:
obj.fit(np.ones((4,3)),np.ones((4,1)))

the bias is [[ 1.  1.  1. -1.]
 [ 1.  1.  1. -1.]
 [ 1.  1.  1. -1.]
 [ 1.  1.  1. -1.]]
